# Generated by Django 3.0.7 on 2020-09-18 05:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import owners.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OwnerProfile',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('profile_pic', models.ImageField(default='profile_pics/user.png', upload_to=owners.models.profile_pic_filename, verbose_name='Profile Picture')),
                ('company', models.CharField(blank=True, max_length=200, verbose_name='Company Name')),
                ('website', models.URLField(blank=True, max_length=254)),
                ('region', models.CharField(max_length=200)),
                ('street', models.CharField(max_length=200)),
            ],
        ),
    ]
