# Generated by Django 3.0.7 on 2020-08-25 06:33

import admins.models
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminProfile',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('profile_pic', models.ImageField(default='profile_pics/user.png', upload_to=admins.models.profile_pic_filename, verbose_name='Profile Picture')),
                ('company', models.CharField(blank=True, max_length=200, verbose_name='Company Name')),
                ('website', models.CharField(blank=True, max_length=200, validators=[django.core.validators.URLValidator()])),
                ('region', models.CharField(max_length=200)),
                ('street', models.CharField(max_length=200)),
            ],
        ),
    ]
