# Generated by Django 3.0.7 on 2020-09-18 05:34

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('email', models.EmailField(max_length=255, unique=True, verbose_name='Email Address')),
                ('name', models.CharField(max_length=100, verbose_name='Full name')),
                ('phone', phonenumber_field.modelfields.PhoneNumberField(help_text='+255 xxx xxx xxx', max_length=128, region=None, verbose_name='Phone Number')),
                ('hear_about_us', models.CharField(choices=[(None, 'Please Select'), ('Whatsapp status', 'Whatsapp status'), ('Internet search', 'Internet Search'), ('Instagram', 'Instagram'), ('Facebook', 'Facebook'), ('Twitter', 'twitter'), ('Linkedln', 'Linkedln'), ('Industry Conference', 'Industry Conference'), ('Industry Publication', 'Industry Publication'), ('Fagrimacs publications', 'Fagrimacs publications'), ('Word of mouth', 'Word of mouth'), ('Other', 'Other')], max_length=150, verbose_name='How did you hear about us?')),
                ('is_active', models.BooleanField(default=False)),
                ('is_expert', models.BooleanField(default=False)),
                ('is_superuser', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
