# Generated by Django 3.0.7 on 2020-08-25 06:33

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('email', models.EmailField(max_length=255, unique=True, verbose_name='Email Address')),
                ('name', models.CharField(max_length=100, verbose_name='Full name')),
                ('phone', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None, verbose_name='Phone Number')),
                ('hear_about_us', models.CharField(choices=[('', 'please select'), ('Whatsapp status', 'Whatsapp status'), ('Internet search', 'Internet Search'), ('Instagram', 'Instagram'), ('Facebook', 'Facebook'), ('Twitter', 'twitter'), ('Linkedln', 'Linkedln'), ('Industry Conference', 'Industry Conference'), ('Industry Publication', 'Industry Publication'), ('Fagrimacs publications', 'Fagrimacs publications'), ('Word of mouth', 'Word of mouth'), ('Other', 'Other')], max_length=150, verbose_name='How did you hear about us?')),
                ('role', models.CharField(choices=[('', 'Please select'), ('farmer', 'Farmer'), ('owner', 'Equipment Owner'), ('expert', 'Expert'), ('admin', 'Admin'), ('superuser', 'Superuser')], max_length=100, verbose_name='What is your primary role in platform?')),
                ('is_active', models.BooleanField(default=False)),
                ('is_superuser', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
