# Generated by Django 3.0.7 on 2020-09-17 06:27

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='hear_about_us',
            field=models.CharField(choices=[(None, 'Please Select'), ('Whatsapp status', 'Whatsapp status'), ('Internet search', 'Internet Search'), ('Instagram', 'Instagram'), ('Facebook', 'Facebook'), ('Twitter', 'twitter'), ('Linkedln', 'Linkedln'), ('Industry Conference', 'Industry Conference'), ('Industry Publication', 'Industry Publication'), ('Fagrimacs publications', 'Fagrimacs publications'), ('Word of mouth', 'Word of mouth'), ('Other', 'Other')], max_length=150, verbose_name='How did you hear about us?'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='phone',
            field=phonenumber_field.modelfields.PhoneNumberField(help_text='+255 xxx xxx xxx', max_length=128, region=None, verbose_name='Phone Number'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[(None, 'Please Select'), ('farmer', 'Farmer'), ('owner', 'Equipment Owner'), ('expert', 'Expert'), ('admin', 'Admin'), ('superuser', 'Superuser')], max_length=100, verbose_name='What is your primary role in platform?'),
        ),
    ]
