# Generated by Django 3.0.7 on 2020-08-16 07:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import multiselectfield.db.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ImplementCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.CreateModel(
            name='Tractor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('tractor_type', models.CharField(choices=[('', 'Please Select'), ('lawn tractor', 'Lawn Tractor'), ('garden tractor', 'Garden Tractor'), ('subcompact tractor', 'Subcompact Tractor'), ('compact utility tractor', 'Compact Utility Tractor'), ('earth moving tractor', 'Earth moving Tractor'), ('industrial type', 'Industrial Tractor Type')], max_length=100, verbose_name='What type of Tractor?')),
                ('drive_type', models.CharField(choices=[('', 'Please Select'), ('two wheel drive', 'Two wheel Drive'), ('four wheel drive', 'Four wheel Drive')], max_length=100, verbose_name='What Drive Type')),
                ('name', models.CharField(help_text='eg. John Deere 6190R', max_length=200, verbose_name='Name/Models of Tractor')),
                ('mode_of_transmission', models.CharField(choices=[('', 'Please Select'), ('gear', 'Gear'), ('manual', 'Manual'), ('hydrostatic', 'Hydrostatic'), ('turbochanged', 'Turbocharged')], max_length=100, verbose_name='Mode of Transmission')),
                ('engine_hp', models.CharField(max_length=100, verbose_name='Engine Horse Power (eng. 75hp)')),
                ('drawbar_hp', models.CharField(max_length=100, verbose_name='Drawbar Horse Power (eng. 65hp)')),
                ('pto_hp', models.CharField(max_length=100, verbose_name='PTO Horse Power (eng. 85hp)')),
                ('hydraulic_capacity', models.CharField(help_text='Use a SI units of gpm or psi', max_length=100, verbose_name='Hydaulic capacity (gallon per minutes(gpm) or psi-pound per square inchies)')),
                ('type_of_hitching', models.CharField(choices=[('', 'Please Select'), ('two point hitches', 'Two-point hitches'), ('three point hitches', 'Three-point hitches')], max_length=100, verbose_name='What is Hitching type?')),
                ('cab', models.CharField(choices=[('', 'Please Select'), ('yes', 'yes'), ('no', 'No')], max_length=100, verbose_name='Does have a cab?')),
                ('rollover_protection', models.CharField(choices=[('', 'Please Select'), ('yes', 'yes'), ('no', 'No')], max_length=100, verbose_name='Does have the rollover protection?')),
                ('fuel_consumption', models.CharField(max_length=100, verbose_name='Fuel consumption (gallon per hour on operation)')),
                ('attachment_mode', models.CharField(choices=[('', 'Please select'), ('frontend loader', 'frontend loader'), ('backhoe', 'Backhoe'), ('both', 'Both')], max_length=100, verbose_name='What mode of attachment?')),
                ('operator', models.CharField(choices=[('', 'Please Select'), ('yes', 'yes'), ('no', 'No')], max_length=100, verbose_name='Do you have an operator(s)?')),
                ('file', models.FileField(help_text='Upload quality picture of real tractor you have, only 5 picture.', upload_to='tractors_photos/', verbose_name='Upload the Tractor pictures')),
                ('other_informations', models.TextField(blank=True, verbose_name='Describe your Tractor')),
                ('price_hour', models.CharField(max_length=100, verbose_name='Specify the price per Hour')),
                ('price_hectare', models.CharField(max_length=100, verbose_name='Specify the price per Hectare')),
                ('farm_services', multiselectfield.db.fields.MultiSelectField(choices=[('', 'Please select'), ('soil cultivations', 'Soil cultivations'), ('planting', 'Planting'), ('haversting/post-haversting', 'Haversting/Post-Haversting'), ('fertilizing & pest-control', 'Fertilizing & Pest-control'), ('drainage & irrigation', 'Drainage & Irrigation'), ('loading', 'Loading'), ('hay making', 'Hay making'), ('miscellaneous', 'Miscellaneous')], max_length=136, verbose_name='What are farming service(s) do you offer?')),
                ('agree_terms', models.BooleanField(default=False, verbose_name='Do your Accept our Terms and Conditions?')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='OtherEquipment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Implement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100, verbose_name='Name/Models of Implement')),
                ('width', models.CharField(help_text='SI UNITS in metre', max_length=50, verbose_name='Width of the Implement')),
                ('weight', models.CharField(help_text='SI UNITS in KG', max_length=50, verbose_name='Weight of the Implement')),
                ('operation_mode', models.CharField(choices=[('', 'Please Select'), ('tractor drive', 'Tractor drive'), ('self-propelled', 'Self-propelled')], max_length=100, verbose_name='What is mode of operation?')),
                ('pto', models.CharField(max_length=100, verbose_name='What is Horse Power required for Operation?')),
                ('hydraulic_capacity', models.CharField(max_length=100, verbose_name='What is Hydaulic capacity required to lift?')),
                ('operator', models.CharField(choices=[('', 'Please Select'), ('yes', 'yes'), ('no', 'No')], max_length=100, verbose_name='Do you have an operator(s)?')),
                ('file', models.FileField(help_text='Upload quality picture of real implement you have, only 5 picture.', upload_to='tractors_photos/', verbose_name='Upload the Implement pictures')),
                ('other_informations', models.TextField(blank=True, verbose_name='Describe your Implement')),
                ('price_hour', models.CharField(max_length=100, verbose_name='Specify the price per Hour')),
                ('price_hectare', models.CharField(max_length=100, verbose_name='Specify the price per Hectare')),
                ('agree_terms', models.BooleanField(default=False, verbose_name='Do your Accept our Terms and Conditions?')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='equipments.ImplementCategory', verbose_name='What category of your Implement')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
