# Generated by Django 3.0.7 on 2020-09-18 05:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import multiselectfield.db.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[(None, 'Please select'), ('tractor', 'Tractor'), ('implement', 'Implement'), ('other_equipment', 'Other Equipment')], max_length=100, verbose_name='What Equipment you want to Add?')),
            ],
        ),
        migrations.CreateModel(
            name='ImplementCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='implements_category')),
            ],
            options={
                'verbose_name_plural': 'Implement Categories',
            },
        ),
        migrations.CreateModel(
            name='Phone',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=18)),
            ],
        ),
        migrations.CreateModel(
            name='TractorCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='tractor_category')),
            ],
            options={
                'verbose_name_plural': 'Tractor Categories',
            },
        ),
        migrations.CreateModel(
            name='Tractor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('drive_type', models.CharField(choices=[(None, 'Please Select'), ('two wheel drive', 'Two wheel Drive'), ('four wheel drive', 'Four wheel Drive')], max_length=100, verbose_name='What Drive Type')),
                ('name', models.CharField(help_text='eg. John Deere 6190R', max_length=200, verbose_name='Name/Models of Tractor')),
                ('mode_of_transmission', models.CharField(choices=[(None, 'Please Select'), ('gear', 'Gear'), ('manual', 'Manual'), ('hydrostatic', 'Hydrostatic'), ('turbochanged', 'Turbocharged')], max_length=100, verbose_name='Mode of Transmission')),
                ('engine_hp', models.PositiveIntegerField(verbose_name='Engine Horse Power (eg. 75hp)')),
                ('drawbar_hp', models.PositiveIntegerField(verbose_name='Drawbar Horse Power (eg. 65hp)')),
                ('pto_hp', models.PositiveIntegerField(verbose_name='PTO Horse Power (eg. 85hp)')),
                ('hydraulic_capacity', models.CharField(help_text='Use a SI units of gpm or psi', max_length=100, verbose_name='Hydaulic capacity (gallon per minutes(gpm) or psi-pound per square inchies)')),
                ('type_of_hitching', models.CharField(choices=[(None, 'Please Select'), ('two point hitches', 'Two-point hitches'), ('three point hitches', 'Three-point hitches')], max_length=100, verbose_name='What is Hitching type?')),
                ('cab', models.BooleanField(default=False, verbose_name='Does have a cab?')),
                ('rollover_protection', models.BooleanField(default=False, verbose_name='Does have the rollover protection?')),
                ('fuel_consumption', models.PositiveIntegerField(verbose_name='Fuel consumption (gallon per hour on operation)')),
                ('attachment_mode', models.CharField(choices=[(None, 'Please select'), ('frontend loader', 'frontend loader'), ('backhoe', 'Backhoe'), ('both', 'Both')], max_length=100, verbose_name='What mode of attachment?')),
                ('operator', models.BooleanField(default=False, verbose_name='Do you have an operator(s)?')),
                ('file', models.FileField(help_text='Upload quality picture of real tractor you have, only 5 picture.', upload_to='tractors_photos/', verbose_name='Upload the Tractor pictures')),
                ('other_informations', models.TextField(blank=True, verbose_name='Describe your Tractor')),
                ('price_hour', models.PositiveIntegerField(verbose_name='Specify the price per Hour in TShs.')),
                ('price_hectare', models.PositiveIntegerField(verbose_name='Specify the price per Hectare')),
                ('farm_services', multiselectfield.db.fields.MultiSelectField(choices=[('soil cultivations', 'Soil cultivations'), ('planting', 'Planting'), ('haversting/post-haversting', 'Haversting/Post-Haversting'), ('fertilizing & pest-control', 'Fertilizing & Pest-control'), ('drainage & irrigation', 'Drainage & Irrigation'), ('loading', 'Loading'), ('hay making', 'Hay making'), ('miscellaneous', 'Miscellaneous')], max_length=135, verbose_name='What are farming service(s) do you offer?')),
                ('agree_terms', models.BooleanField(default=False, verbose_name='Do your Accept our Terms and Conditions?')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved')], default='pending', max_length=100)),
                ('tractor_type', models.ForeignKey(on_delete=models.SET('others'), to='equipments.TractorCategory', verbose_name='What type of Tractor?')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ImplementSubCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='equipments.ImplementCategory')),
            ],
            options={
                'verbose_name_plural': 'Implement Subcategories',
            },
        ),
        migrations.CreateModel(
            name='Implement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100, verbose_name='Name/Models of Implement')),
                ('width', models.PositiveIntegerField(help_text='SI UNITS in metre', verbose_name='Width of the Implement')),
                ('weight', models.PositiveIntegerField(help_text='SI UNITS in KG', verbose_name='Weight of the Implement')),
                ('operation_mode', models.CharField(choices=[(None, 'Please Select'), ('tractor drive', 'Tractor drive'), ('self-propelled', 'Self-propelled')], max_length=100, verbose_name='What is mode of operation?')),
                ('pto', models.PositiveIntegerField(verbose_name='What is Horse Power required for Operation?')),
                ('hydraulic_capacity', models.CharField(max_length=100, verbose_name='What is Hydaulic capacity required to lift?')),
                ('operator', models.BooleanField(verbose_name='Do you have an operator(s)?')),
                ('file', models.FileField(help_text='Upload quality picture of real implement you have, only 5 pictures.', upload_to='implements_photos/', verbose_name='Upload the Implement pictures')),
                ('other_informations', models.TextField(blank=True, verbose_name='Describe your Implement')),
                ('price_hour', models.PositiveIntegerField(verbose_name='Specify the price per Hour')),
                ('price_hectare', models.PositiveIntegerField(verbose_name='Specify the price per Hectare')),
                ('agree_terms', models.BooleanField(default=False, verbose_name='Do your Accept our Terms and Conditions?')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved')], default='pending', max_length=100)),
                ('category', models.ForeignKey(on_delete=models.SET('others'), to='equipments.ImplementCategory', verbose_name='What category of your Implement')),
                ('subcategory', models.ForeignKey(on_delete=models.SET('others'), to='equipments.ImplementSubCategory', verbose_name='What is subcategory of your Implement')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
