# Generated by Django 3.0.7 on 2020-08-25 06:34

from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('equipments', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('', 'Please select'), ('tractor', 'Tractor'), ('implement', 'Implement'), ('other_equipment', 'Other Equipment')], max_length=100, verbose_name='What Equipment you want to Add?')),
            ],
        ),
        migrations.CreateModel(
            name='Phone',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=18)),
            ],
        ),
        migrations.AddField(
            model_name='implement',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved')], default='pending', max_length=100),
        ),
        migrations.AddField(
            model_name='tractor',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved')], default='pending', max_length=100),
        ),
        migrations.AlterField(
            model_name='tractor',
            name='drawbar_hp',
            field=models.CharField(max_length=100, verbose_name='Drawbar Horse Power (eg. 65hp)'),
        ),
        migrations.AlterField(
            model_name='tractor',
            name='engine_hp',
            field=models.CharField(max_length=100, verbose_name='Engine Horse Power (eg. 75hp)'),
        ),
        migrations.AlterField(
            model_name='tractor',
            name='farm_services',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('soil cultivations', 'Soil cultivations'), ('planting', 'Planting'), ('haversting/post-haversting', 'Haversting/Post-Haversting'), ('fertilizing & pest-control', 'Fertilizing & Pest-control'), ('drainage & irrigation', 'Drainage & Irrigation'), ('loading', 'Loading'), ('hay making', 'Hay making'), ('miscellaneous', 'Miscellaneous')], max_length=135, verbose_name='What are farming service(s) do you offer?'),
        ),
        migrations.AlterField(
            model_name='tractor',
            name='pto_hp',
            field=models.CharField(max_length=100, verbose_name='PTO Horse Power (eg. 85hp)'),
        ),
        migrations.DeleteModel(
            name='OtherEquipment',
        ),
    ]
