# Generated by Django 3.0.7 on 2020-09-24 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipments', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Equipment',
        ),
        migrations.DeleteModel(
            name='Phone',
        ),
        migrations.RemoveField(
            model_name='implement',
            name='status',
        ),
        migrations.RemoveField(
            model_name='tractor',
            name='status',
        ),
        migrations.AddField(
            model_name='implement',
            name='approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='tractor',
            name='approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='implementcategory',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='implements_category'),
        ),
        migrations.AlterField(
            model_name='tractorcategory',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='tractor_category'),
        ),
    ]
