# Generated by Django 3.0.7 on 2020-09-22 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipments', '0002_auto_20200922_1035'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tractorcategory',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='tractor_category'),
        ),
    ]
