# Generated by Django 3.0.7 on 2020-08-26 12:59

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('equipments', '0002_auto_20200825_0933'),
    ]

    operations = [
        migrations.CreateModel(
            name='TractorCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='tractor_category')),
            ],
        ),
        migrations.AlterModelOptions(
            name='implementcategory',
            options={},
        ),
        migrations.AddField(
            model_name='implementcategory',
            name='image',
            field=models.ImageField(default=django.utils.timezone.now, upload_to='implements_category'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='implement',
            name='category',
            field=models.ForeignKey(on_delete=models.SET('others'), to='equipments.ImplementCategory', verbose_name='What category of your Implement'),
        ),
        migrations.AlterField(
            model_name='implement',
            name='file',
            field=models.FileField(help_text='Upload quality picture of real implement you have, only 5 picture.', upload_to='implements_photos/', verbose_name='Upload the Implement pictures'),
        ),
        migrations.AlterField(
            model_name='tractor',
            name='tractor_type',
            field=models.ForeignKey(on_delete=models.SET('others'), to='equipments.TractorCategory', verbose_name='What type of Tractor?'),
        ),
    ]
