# Generated by Django 3.0.7 on 2020-08-26 13:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('equipments', '0003_auto_20200826_1559'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImplementSubCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='equipments.ImplementCategory')),
            ],
        ),
        migrations.AddField(
            model_name='implement',
            name='subcategory',
            field=models.ForeignKey(default=1, on_delete=models.SET('others'), to='equipments.ImplementSubCategory', verbose_name='What is subcategory of your Implement'),
            preserve_default=False,
        ),
    ]
