# Generated by Django 3.0.7 on 2020-09-17 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipments', '0004_auto_20200826_1653'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='implementcategory',
            options={'verbose_name_plural': 'Implement Categories'},
        ),
        migrations.AlterModelOptions(
            name='implementsubcategory',
            options={'verbose_name_plural': 'Implement Subcategories'},
        ),
        migrations.AlterModelOptions(
            name='tractorcategory',
            options={'verbose_name_plural': 'Tractor Categories'},
        ),
        migrations.AlterField(
            model_name='equipment',
            name='type',
            field=models.CharField(choices=[(None, 'Please select'), ('tractor', 'Tractor'), ('implement', 'Implement'), ('other_equipment', 'Other Equipment')], max_length=100, verbose_name='What Equipment you want to Add?'),
        ),
        migrations.AlterField(
            model_name='implement',
            name='file',
            field=models.FileField(help_text='Upload quality picture of real implement you have, only 5 pictures.', upload_to='implements_photos/', verbose_name='Upload the Implement pictures'),
        ),
        migrations.AlterField(
            model_name='implement',
            name='operation_mode',
            field=models.CharField(choices=[(None, 'Please Select'), ('tractor drive', 'Tractor drive'), ('self-propelled', 'Self-propelled')], max_length=100, verbose_name='What is mode of operation?'),
        ),
        migrations.AlterField(
            model_name='implement',
            name='operator',
            field=models.BooleanField(verbose_name='Do you have an operator(s)?'),
        ),
        migrations.AlterField(
            model_name='implement',
            name='price_hectare',
            field=models.PositiveIntegerField(verbose_name='Specify the price per Hectare'),
        ),
        migrations.AlterField(
            model_name='implement',
            name='price_hour',
            field=models.PositiveIntegerField(verbose_name='Specify the price per Hour'),
        ),
        migrations.AlterField(
            model_name='implement',
            name='pto',
            field=models.PositiveIntegerField(verbose_name='What is Horse Power required for Operation?'),
        ),
        migrations.AlterField(
            model_name='implement',
            name='weight',
            field=models.PositiveIntegerField(help_text='SI UNITS in KG', verbose_name='Weight of the Implement'),
        ),
        migrations.AlterField(
            model_name='implement',
            name='width',
            field=models.PositiveIntegerField(help_text='SI UNITS in metre', verbose_name='Width of the Implement'),
        ),
        migrations.AlterField(
            model_name='tractor',
            name='attachment_mode',
            field=models.CharField(choices=[(None, 'Please select'), ('frontend loader', 'frontend loader'), ('backhoe', 'Backhoe'), ('both', 'Both')], max_length=100, verbose_name='What mode of attachment?'),
        ),
        migrations.AlterField(
            model_name='tractor',
            name='cab',
            field=models.BooleanField(verbose_name='Does have a cab?'),
        ),
        migrations.AlterField(
            model_name='tractor',
            name='drawbar_hp',
            field=models.PositiveIntegerField(verbose_name='Drawbar Horse Power (eg. 65hp)'),
        ),
        migrations.AlterField(
            model_name='tractor',
            name='drive_type',
            field=models.CharField(choices=[(None, 'Please Select'), ('two wheel drive', 'Two wheel Drive'), ('four wheel drive', 'Four wheel Drive')], max_length=100, verbose_name='What Drive Type'),
        ),
        migrations.AlterField(
            model_name='tractor',
            name='engine_hp',
            field=models.PositiveIntegerField(verbose_name='Engine Horse Power (eg. 75hp)'),
        ),
        migrations.AlterField(
            model_name='tractor',
            name='fuel_consumption',
            field=models.PositiveIntegerField(verbose_name='Fuel consumption (gallon per hour on operation)'),
        ),
        migrations.AlterField(
            model_name='tractor',
            name='mode_of_transmission',
            field=models.CharField(choices=[(None, 'Please Select'), ('gear', 'Gear'), ('manual', 'Manual'), ('hydrostatic', 'Hydrostatic'), ('turbochanged', 'Turbocharged')], max_length=100, verbose_name='Mode of Transmission'),
        ),
        migrations.AlterField(
            model_name='tractor',
            name='operator',
            field=models.BooleanField(default=False, verbose_name='Do you have an operator(s)?'),
        ),
        migrations.AlterField(
            model_name='tractor',
            name='price_hectare',
            field=models.PositiveIntegerField(verbose_name='Specify the price per Hectare'),
        ),
        migrations.AlterField(
            model_name='tractor',
            name='price_hour',
            field=models.PositiveIntegerField(verbose_name='Specify the price per Hour in TShs.'),
        ),
        migrations.AlterField(
            model_name='tractor',
            name='pto_hp',
            field=models.PositiveIntegerField(verbose_name='PTO Horse Power (eg. 85hp)'),
        ),
        migrations.AlterField(
            model_name='tractor',
            name='rollover_protection',
            field=models.BooleanField(verbose_name='Does have the rollover protection?'),
        ),
        migrations.AlterField(
            model_name='tractor',
            name='type_of_hitching',
            field=models.CharField(choices=[(None, 'Please Select'), ('two point hitches', 'Two-point hitches'), ('three point hitches', 'Three-point hitches')], max_length=100, verbose_name='What is Hitching type?'),
        ),
    ]
