# Generated by Django 3.0.7 on 2020-09-17 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipments', '0005_auto_20200917_0927'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tractor',
            name='cab',
            field=models.BooleanField(default=False, verbose_name='Does have a cab?'),
        ),
        migrations.AlterField(
            model_name='tractor',
            name='rollover_protection',
            field=models.BooleanField(default=False, verbose_name='Does have the rollover protection?'),
        ),
    ]
