# Generated by Django 3.0.7 on 2020-09-18 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('experts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expertprofile',
            name='website',
            field=models.URLField(blank=True, max_length=254),
        ),
    ]
