# Generated by Django 3.0.7 on 2020-09-17 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farmers', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='farmerprofile',
            name='website',
            field=models.URLField(blank=True, max_length=254),
        ),
    ]
